import { Session } from "@supabase/supabase-js";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { supabase } from "../utils/supabaseClient";
import Account from "./new-user";
import Auth from "./login";
import NewUser from "./new-user";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [session, setSession] = useState<null | Session>(null);
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Mocial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="prose"></main>
    </div>
  );
};

export default Home;
